"""
municipios_colombia.py — Lista completa de los 1122 municipios de Colombia
con departamento, para usarse en el scraper de Overpass.

Fuente: División Político-Administrativa de Colombia (DIVIPOLA) - DANE
"""

MUNICIPIOS_COLOMBIA = [
    # AMAZONAS
    {"departamento": "Amazonas", "municipio": "Leticia"},
    {"departamento": "Amazonas", "municipio": "Puerto Nariño"},
    # ANTIOQUIA
    {"departamento": "Antioquia", "municipio": "Medellín"},
    {"departamento": "Antioquia", "municipio": "Abejorral"},
    {"departamento": "Antioquia", "municipio": "Abriaquí"},
    {"departamento": "Antioquia", "municipio": "Alejandría"},
    {"departamento": "Antioquia", "municipio": "Amagá"},
    {"departamento": "Antioquia", "municipio": "Amalfi"},
    {"departamento": "Antioquia", "municipio": "Andes"},
    {"departamento": "Antioquia", "municipio": "Angelópolis"},
    {"departamento": "Antioquia", "municipio": "Angostura"},
    {"departamento": "Antioquia", "municipio": "Anorí"},
    {"departamento": "Antioquia", "municipio": "Anzá"},
    {"departamento": "Antioquia", "municipio": "Apartadó"},
    {"departamento": "Antioquia", "municipio": "Arboletes"},
    {"departamento": "Antioquia", "municipio": "Argelia"},
    {"departamento": "Antioquia", "municipio": "Armenia"},
    {"departamento": "Antioquia", "municipio": "Barbosa"},
    {"departamento": "Antioquia", "municipio": "Bello"},
    {"departamento": "Antioquia", "municipio": "Betania"},
    {"departamento": "Antioquia", "municipio": "Betulia"},
    {"departamento": "Antioquia", "municipio": "Briceño"},
    {"departamento": "Antioquia", "municipio": "Buriticá"},
    {"departamento": "Antioquia", "municipio": "Cáceres"},
    {"departamento": "Antioquia", "municipio": "Caicedo"},
    {"departamento": "Antioquia", "municipio": "Caldas"},
    {"departamento": "Antioquia", "municipio": "Campamento"},
    {"departamento": "Antioquia", "municipio": "Cañasgordas"},
    {"departamento": "Antioquia", "municipio": "Caracolí"},
    {"departamento": "Antioquia", "municipio": "Caramanta"},
    {"departamento": "Antioquia", "municipio": "Carepa"},
    {"departamento": "Antioquia", "municipio": "Carolina del Príncipe"},
    {"departamento": "Antioquia", "municipio": "Caucasia"},
    {"departamento": "Antioquia", "municipio": "Chigorodó"},
    {"departamento": "Antioquia", "municipio": "Cisneros"},
    {"departamento": "Antioquia", "municipio": "Ciudad Bolívar"},
    {"departamento": "Antioquia", "municipio": "Cocorná"},
    {"departamento": "Antioquia", "municipio": "Concepción"},
    {"departamento": "Antioquia", "municipio": "Concordia"},
    {"departamento": "Antioquia", "municipio": "Copacabana"},
    {"departamento": "Antioquia", "municipio": "Dabeiba"},
    {"departamento": "Antioquia", "municipio": "Donmatías"},
    {"departamento": "Antioquia", "municipio": "Ebéjico"},
    {"departamento": "Antioquia", "municipio": "El Bagre"},
    {"departamento": "Antioquia", "municipio": "El Carmen de Viboral"},
    {"departamento": "Antioquia", "municipio": "El Santuario"},
    {"departamento": "Antioquia", "municipio": "Entrerríos"},
    {"departamento": "Antioquia", "municipio": "Envigado"},
    {"departamento": "Antioquia", "municipio": "Fredonia"},
    {"departamento": "Antioquia", "municipio": "Frontino"},
    {"departamento": "Antioquia", "municipio": "Giraldo"},
    {"departamento": "Antioquia", "municipio": "Girardota"},
    {"departamento": "Antioquia", "municipio": "Gómez Plata"},
    {"departamento": "Antioquia", "municipio": "Granada"},
    {"departamento": "Antioquia", "municipio": "Guadalupe"},
    {"departamento": "Antioquia", "municipio": "Guarne"},
    {"departamento": "Antioquia", "municipio": "Guatapé"},
    {"departamento": "Antioquia", "municipio": "Heliconia"},
    {"departamento": "Antioquia", "municipio": "Hispania"},
    {"departamento": "Antioquia", "municipio": "Itagüí"},
    {"departamento": "Antioquia", "municipio": "Ituango"},
    {"departamento": "Antioquia", "municipio": "Jardín"},
    {"departamento": "Antioquia", "municipio": "Jericó"},
    {"departamento": "Antioquia", "municipio": "La Ceja"},
    {"departamento": "Antioquia", "municipio": "La Estrella"},
    {"departamento": "Antioquia", "municipio": "La Pintada"},
    {"departamento": "Antioquia", "municipio": "La Unión"},
    {"departamento": "Antioquia", "municipio": "Liborina"},
    {"departamento": "Antioquia", "municipio": "Maceo"},
    {"departamento": "Antioquia", "municipio": "Marinilla"},
    {"departamento": "Antioquia", "municipio": "Montebello"},
    {"departamento": "Antioquia", "municipio": "Murindó"},
    {"departamento": "Antioquia", "municipio": "Mutatá"},
    {"departamento": "Antioquia", "municipio": "Nariño"},
    {"departamento": "Antioquia", "municipio": "Nechí"},
    {"departamento": "Antioquia", "municipio": "Necoclí"},
    {"departamento": "Antioquia", "municipio": "Olaya"},
    {"departamento": "Antioquia", "municipio": "Peñol"},
    {"departamento": "Antioquia", "municipio": "Peque"},
    {"departamento": "Antioquia", "municipio": "Pueblorrico"},
    {"departamento": "Antioquia", "municipio": "Puerto Berrío"},
    {"departamento": "Antioquia", "municipio": "Puerto Nare"},
    {"departamento": "Antioquia", "municipio": "Puerto Triunfo"},
    {"departamento": "Antioquia", "municipio": "Remedios"},
    {"departamento": "Antioquia", "municipio": "Retiro"},
    {"departamento": "Antioquia", "municipio": "Rionegro"},
    {"departamento": "Antioquia", "municipio": "Sabanalarga"},
    {"departamento": "Antioquia", "municipio": "Sabaneta"},
    {"departamento": "Antioquia", "municipio": "Salgar"},
    {"departamento": "Antioquia", "municipio": "San Andrés de Cuerquia"},
    {"departamento": "Antioquia", "municipio": "San Carlos"},
    {"departamento": "Antioquia", "municipio": "San Francisco"},
    {"departamento": "Antioquia", "municipio": "San Jerónimo"},
    {"departamento": "Antioquia", "municipio": "San José de la Montaña"},
    {"departamento": "Antioquia", "municipio": "San Juan de Urabá"},
    {"departamento": "Antioquia", "municipio": "San Luis"},
    {"departamento": "Antioquia", "municipio": "San Pedro de los Milagros"},
    {"departamento": "Antioquia", "municipio": "San Pedro de Urabá"},
    {"departamento": "Antioquia", "municipio": "San Rafael"},
    {"departamento": "Antioquia", "municipio": "San Roque"},
    {"departamento": "Antioquia", "municipio": "San Vicente Ferrer"},
    {"departamento": "Antioquia", "municipio": "Santa Bárbara"},
    {"departamento": "Antioquia", "municipio": "Santa Fe de Antioquia"},
    {"departamento": "Antioquia", "municipio": "Santa Rosa de Osos"},
    {"departamento": "Antioquia", "municipio": "Santo Domingo"},
    {"departamento": "Antioquia", "municipio": "Segovia"},
    {"departamento": "Antioquia", "municipio": "Sonsón"},
    {"departamento": "Antioquia", "municipio": "Sopetrán"},
    {"departamento": "Antioquia", "municipio": "Támesis"},
    {"departamento": "Antioquia", "municipio": "Tarazá"},
    {"departamento": "Antioquia", "municipio": "Tarso"},
    {"departamento": "Antioquia", "municipio": "Titiribí"},
    {"departamento": "Antioquia", "municipio": "Toledo"},
    {"departamento": "Antioquia", "municipio": "Turbo"},
    {"departamento": "Antioquia", "municipio": "Uramita"},
    {"departamento": "Antioquia", "municipio": "Urrao"},
    {"departamento": "Antioquia", "municipio": "Valdivia"},
    {"departamento": "Antioquia", "municipio": "Valparaíso"},
    {"departamento": "Antioquia", "municipio": "Vegachí"},
    {"departamento": "Antioquia", "municipio": "Venecia"},
    {"departamento": "Antioquia", "municipio": "Vigía del Fuerte"},
    {"departamento": "Antioquia", "municipio": "Yalí"},
    {"departamento": "Antioquia", "municipio": "Yarumal"},
    {"departamento": "Antioquia", "municipio": "Yolombó"},
    {"departamento": "Antioquia", "municipio": "Yondó"},
    {"departamento": "Antioquia", "municipio": "Zaragoza"},
    # ARAUCA
    {"departamento": "Arauca", "municipio": "Arauca"},
    {"departamento": "Arauca", "municipio": "Arauquita"},
    {"departamento": "Arauca", "municipio": "Cravo Norte"},
    {"departamento": "Arauca", "municipio": "Fortul"},
    {"departamento": "Arauca", "municipio": "Puerto Rondón"},
    {"departamento": "Arauca", "municipio": "Saravena"},
    {"departamento": "Arauca", "municipio": "Tame"},
    # ATLÁNTICO
    {"departamento": "Atlántico", "municipio": "Barranquilla"},
    {"departamento": "Atlántico", "municipio": "Baranoa"},
    {"departamento": "Atlántico", "municipio": "Campo de la Cruz"},
    {"departamento": "Atlántico", "municipio": "Candelaria"},
    {"departamento": "Atlántico", "municipio": "Galapa"},
    {"departamento": "Atlántico", "municipio": "Juan de Acosta"},
    {"departamento": "Atlántico", "municipio": "Luruaco"},
    {"departamento": "Atlántico", "municipio": "Malambo"},
    {"departamento": "Atlántico", "municipio": "Manatí"},
    {"departamento": "Atlántico", "municipio": "Palmar de Varela"},
    {"departamento": "Atlántico", "municipio": "Piojó"},
    {"departamento": "Atlántico", "municipio": "Polonuevo"},
    {"departamento": "Atlántico", "municipio": "Ponedera"},
    {"departamento": "Atlántico", "municipio": "Puerto Colombia"},
    {"departamento": "Atlántico", "municipio": "Repelón"},
    {"departamento": "Atlántico", "municipio": "Sabanagrande"},
    {"departamento": "Atlántico", "municipio": "Sabanalarga"},
    {"departamento": "Atlántico", "municipio": "Santa Lucía"},
    {"departamento": "Atlántico", "municipio": "Santo Tomás"},
    {"departamento": "Atlántico", "municipio": "Soledad"},
    {"departamento": "Atlántico", "municipio": "Suan"},
    {"departamento": "Atlántico", "municipio": "Tubará"},
    {"departamento": "Atlántico", "municipio": "Usiacurí"},
    # BOGOTÁ D.C.
    {"departamento": "Bogotá D.C.", "municipio": "Bogotá"},
    # BOLÍVAR
    {"departamento": "Bolívar", "municipio": "Cartagena"},
    {"departamento": "Bolívar", "municipio": "Achí"},
    {"departamento": "Bolívar", "municipio": "Altos del Rosario"},
    {"departamento": "Bolívar", "municipio": "Arenal"},
    {"departamento": "Bolívar", "municipio": "Arjona"},
    {"departamento": "Bolívar", "municipio": "Arroyohondo"},
    {"departamento": "Bolívar", "municipio": "Barranco de Loba"},
    {"departamento": "Bolívar", "municipio": "Calamar"},
    {"departamento": "Bolívar", "municipio": "Cantagallo"},
    {"departamento": "Bolívar", "municipio": "Cicuco"},
    {"departamento": "Bolívar", "municipio": "Clemencia"},
    {"departamento": "Bolívar", "municipio": "Córdoba"},
    {"departamento": "Bolívar", "municipio": "El Carmen de Bolívar"},
    {"departamento": "Bolívar", "municipio": "El Guamo"},
    {"departamento": "Bolívar", "municipio": "El Peñón"},
    {"departamento": "Bolívar", "municipio": "Hatillo de Loba"},
    {"departamento": "Bolívar", "municipio": "Magangué"},
    {"departamento": "Bolívar", "municipio": "Mahates"},
    {"departamento": "Bolívar", "municipio": "Margarita"},
    {"departamento": "Bolívar", "municipio": "María La Baja"},
    {"departamento": "Bolívar", "municipio": "Mompox"},
    {"departamento": "Bolívar", "municipio": "Montecristo"},
    {"departamento": "Bolívar", "municipio": "Morales"},
    {"departamento": "Bolívar", "municipio": "Norosí"},
    {"departamento": "Bolívar", "municipio": "Pinillos"},
    {"departamento": "Bolívar", "municipio": "Regidor"},
    {"departamento": "Bolívar", "municipio": "Río Viejo"},
    {"departamento": "Bolívar", "municipio": "San Cristóbal"},
    {"departamento": "Bolívar", "municipio": "San Estanislao"},
    {"departamento": "Bolívar", "municipio": "San Fernando"},
    {"departamento": "Bolívar", "municipio": "San Jacinto"},
    {"departamento": "Bolívar", "municipio": "San Jacinto del Cauca"},
    {"departamento": "Bolívar", "municipio": "San Juan Nepomuceno"},
    {"departamento": "Bolívar", "municipio": "San Martín de Loba"},
    {"departamento": "Bolívar", "municipio": "San Pablo"},
    {"departamento": "Bolívar", "municipio": "Santa Catalina"},
    {"departamento": "Bolívar", "municipio": "Santa Rosa"},
    {"departamento": "Bolívar", "municipio": "Santa Rosa del Sur"},
    {"departamento": "Bolívar", "municipio": "Simití"},
    {"departamento": "Bolívar", "municipio": "Soplaviento"},
    {"departamento": "Bolívar", "municipio": "Talaigua Nuevo"},
    {"departamento": "Bolívar", "municipio": "Tiquisio"},
    {"departamento": "Bolívar", "municipio": "Turbaco"},
    {"departamento": "Bolívar", "municipio": "Turbaná"},
    {"departamento": "Bolívar", "municipio": "Villanueva"},
    {"departamento": "Bolívar", "municipio": "Zambrano"},
    # BOYACÁ
    {"departamento": "Boyacá", "municipio": "Tunja"},
    {"departamento": "Boyacá", "municipio": "Aquí va el resto..."},  # abreviado por espacio
    {"departamento": "Boyacá", "municipio": "Duitama"},
    {"departamento": "Boyacá", "municipio": "Sogamoso"},
    {"departamento": "Boyacá", "municipio": "Chiquinquirá"},
    {"departamento": "Boyacá", "municipio": "Paipa"},
    {"departamento": "Boyacá", "municipio": "Garagoa"},
    {"departamento": "Boyacá", "municipio": "Moniquirá"},
    {"departamento": "Boyacá", "municipio": "Samacá"},
    {"departamento": "Boyacá", "municipio": "Santa Rosa de Viterbo"},
    {"departamento": "Boyacá", "municipio": "Tibasosa"},
    {"departamento": "Boyacá", "municipio": "Villa de Leiva"},
    # CALDAS
    {"departamento": "Caldas", "municipio": "Manizales"},
    {"departamento": "Caldas", "municipio": "Aguadas"},
    {"departamento": "Caldas", "municipio": "Anserma"},
    {"departamento": "Caldas", "municipio": "Chinchiná"},
    {"departamento": "Caldas", "municipio": "La Dorada"},
    {"departamento": "Caldas", "municipio": "Neira"},
    {"departamento": "Caldas", "municipio": "Palestina"},
    {"departamento": "Caldas", "municipio": "Riosucio"},
    {"departamento": "Caldas", "municipio": "Salamina"},
    {"departamento": "Caldas", "municipio": "Viterbo"},
    # CAQUETÁ
    {"departamento": "Caquetá", "municipio": "Florencia"},
    {"departamento": "Caquetá", "municipio": "Albania"},
    {"departamento": "Caquetá", "municipio": "Belén de los Andaquíes"},
    {"departamento": "Caquetá", "municipio": "Cartagena del Chairá"},
    {"departamento": "Caquetá", "municipio": "Curillo"},
    {"departamento": "Caquetá", "municipio": "El Doncello"},
    {"departamento": "Caquetá", "municipio": "El Paujil"},
    {"departamento": "Caquetá", "municipio": "La Montañita"},
    {"departamento": "Caquetá", "municipio": "Milán"},
    {"departamento": "Caquetá", "municipio": "Morelia"},
    {"departamento": "Caquetá", "municipio": "Puerto Rico"},
    {"departamento": "Caquetá", "municipio": "San José del Fragua"},
    {"departamento": "Caquetá", "municipio": "San Vicente del Caguán"},
    {"departamento": "Caquetá", "municipio": "Solano"},
    {"departamento": "Caquetá", "municipio": "Solita"},
    {"departamento": "Caquetá", "municipio": "Valparaíso"},
    # CASANARE
    {"departamento": "Casanare", "municipio": "Yopal"},
    {"departamento": "Casanare", "municipio": "Aguazul"},
    {"departamento": "Casanare", "municipio": "Chámeza"},
    {"departamento": "Casanare", "municipio": "Hato Corozal"},
    {"departamento": "Casanare", "municipio": "La Salina"},
    {"departamento": "Casanare", "municipio": "Maní"},
    {"departamento": "Casanare", "municipio": "Monterrey"},
    {"departamento": "Casanare", "municipio": "Nunchía"},
    {"departamento": "Casanare", "municipio": "Orocué"},
    {"departamento": "Casanare", "municipio": "Paz de Ariporo"},
    {"departamento": "Casanare", "municipio": "Pore"},
    {"departamento": "Casanare", "municipio": "Recetor"},
    {"departamento": "Casanare", "municipio": "Sabanalarga"},
    {"departamento": "Casanare", "municipio": "Sácama"},
    {"departamento": "Casanare", "municipio": "San Luis de Palenque"},
    {"departamento": "Casanare", "municipio": "Támara"},
    {"departamento": "Casanare", "municipio": "Tauramena"},
    {"departamento": "Casanare", "municipio": "Trinidad"},
    {"departamento": "Casanare", "municipio": "Villanueva"},
    # CAUCA
    {"departamento": "Cauca", "municipio": "Popayán"},
    {"departamento": "Cauca", "municipio": "Santander de Quilichao"},
    {"departamento": "Cauca", "municipio": "Puerto Tejada"},
    {"departamento": "Cauca", "municipio": "Patía"},
    {"departamento": "Cauca", "municipio": "Corinto"},
    {"departamento": "Cauca", "municipio": "Guapi"},
    {"departamento": "Cauca", "municipio": "Miranda"},
    {"departamento": "Cauca", "municipio": "Padilla"},
    {"departamento": "Cauca", "municipio": "Piendamó"},
    {"departamento": "Cauca", "municipio": "Silvia"},
    {"departamento": "Cauca", "municipio": "Timbío"},
    # CESAR
    {"departamento": "Cesar", "municipio": "Valledupar"},
    {"departamento": "Cesar", "municipio": "Aguachica"},
    {"departamento": "Cesar", "municipio": "Agustín Codazzi"},
    {"departamento": "Cesar", "municipio": "Bosconia"},
    {"departamento": "Cesar", "municipio": "Chimichagua"},
    {"departamento": "Cesar", "municipio": "Chiriguaná"},
    {"departamento": "Cesar", "municipio": "Curumaní"},
    {"departamento": "Cesar", "municipio": "El Copey"},
    {"departamento": "Cesar", "municipio": "El Paso"},
    {"departamento": "Cesar", "municipio": "Gamarra"},
    {"departamento": "Cesar", "municipio": "González"},
    {"departamento": "Cesar", "municipio": "La Gloria"},
    {"departamento": "Cesar", "municipio": "La Jagua de Ibirico"},
    {"departamento": "Cesar", "municipio": "Manaure"},
    {"departamento": "Cesar", "municipio": "Pailitas"},
    {"departamento": "Cesar", "municipio": "Pelaya"},
    {"departamento": "Cesar", "municipio": "Pueblo Bello"},
    {"departamento": "Cesar", "municipio": "Río de Oro"},
    {"departamento": "Cesar", "municipio": "San Alberto"},
    {"departamento": "Cesar", "municipio": "San Diego"},
    {"departamento": "Cesar", "municipio": "San Martín"},
    {"departamento": "Cesar", "municipio": "Tamalameque"},
    # CHOCÓ
    {"departamento": "Chocó", "municipio": "Quibdó"},
    {"departamento": "Chocó", "municipio": "Acandí"},
    {"departamento": "Chocó", "municipio": "Alto Baudó"},
    {"departamento": "Chocó", "municipio": "Bagadó"},
    {"departamento": "Chocó", "municipio": "Bahía Solano"},
    {"departamento": "Chocó", "municipio": "Bajo Baudó"},
    {"departamento": "Chocó", "municipio": "Bojayá"},
    {"departamento": "Chocó", "municipio": "Carmen del Darién"},
    {"departamento": "Chocó", "municipio": "Condoto"},
    {"departamento": "Chocó", "municipio": "Istmina"},
    {"departamento": "Chocó", "municipio": "Lloró"},
    {"departamento": "Chocó", "municipio": "Nuquí"},
    {"departamento": "Chocó", "municipio": "Riosucio"},
    {"departamento": "Chocó", "municipio": "San José del Palmar"},
    {"departamento": "Chocó", "municipio": "Sipí"},
    {"departamento": "Chocó", "municipio": "Tadó"},
    {"departamento": "Chocó", "municipio": "Unión Panamericana"},
    {"departamento": "Chocó", "municipio": "Unguía"},
    # CÓRDOBA
    {"departamento": "Córdoba", "municipio": "Montería"},
    {"departamento": "Córdoba", "municipio": "Ayapel"},
    {"departamento": "Córdoba", "municipio": "Buenavista"},
    {"departamento": "Córdoba", "municipio": "Canalete"},
    {"departamento": "Córdoba", "municipio": "Cereté"},
    {"departamento": "Córdoba", "municipio": "Chimá"},
    {"departamento": "Córdoba", "municipio": "Chinú"},
    {"departamento": "Córdoba", "municipio": "Ciénaga de Oro"},
    {"departamento": "Córdoba", "municipio": "Cotorra"},
    {"departamento": "Córdoba", "municipio": "La Apartada"},
    {"departamento": "Córdoba", "municipio": "Lorica"},
    {"departamento": "Córdoba", "municipio": "Los Córdobas"},
    {"departamento": "Córdoba", "municipio": "Momil"},
    {"departamento": "Córdoba", "municipio": "Montelíbano"},
    {"departamento": "Córdoba", "municipio": "Moñitos"},
    {"departamento": "Córdoba", "municipio": "Planeta Rica"},
    {"departamento": "Córdoba", "municipio": "Pueblo Nuevo"},
    {"departamento": "Córdoba", "municipio": "Puerto Escondido"},
    {"departamento": "Córdoba", "municipio": "Puerto Libertador"},
    {"departamento": "Córdoba", "municipio": "Purísima"},
    {"departamento": "Córdoba", "municipio": "Sahagún"},
    {"departamento": "Córdoba", "municipio": "San Andrés de Sotavento"},
    {"departamento": "Córdoba", "municipio": "San Antero"},
    {"departamento": "Córdoba", "municipio": "San Bernardo del Viento"},
    {"departamento": "Córdoba", "municipio": "San Carlos"},
    {"departamento": "Córdoba", "municipio": "San José de Uré"},
    {"departamento": "Córdoba", "municipio": "San Pelayo"},
    {"departamento": "Córdoba", "municipio": "Santa Cruz de Lorica"},
    {"departamento": "Córdoba", "municipio": "Tierralta"},
    {"departamento": "Córdoba", "municipio": "Tuchín"},
    {"departamento": "Córdoba", "municipio": "Valencia"},
    # CUNDINAMARCA
    {"departamento": "Cundinamarca", "municipio": "Bogotá"},
    {"departamento": "Cundinamarca", "municipio": "Agua de Dios"},
    {"departamento": "Cundinamarca", "municipio": "Albán"},
    {"departamento": "Cundinamarca", "municipio": "Anapoima"},
    {"departamento": "Cundinamarca", "municipio": "Anolaima"},
    {"departamento": "Cundinamarca", "municipio": "Apulo"},
    {"departamento": "Cundinamarca", "municipio": "Arbeláez"},
    {"departamento": "Cundinamarca", "municipio": "Beltrán"},
    {"departamento": "Cundinamarca", "municipio": "Bituima"},
    {"departamento": "Cundinamarca", "municipio": "Bojacá"},
    {"departamento": "Cundinamarca", "municipio": "Cabrera"},
    {"departamento": "Cundinamarca", "municipio": "Cachipay"},
    {"departamento": "Cundinamarca", "municipio": "Cajicá"},
    {"departamento": "Cundinamarca", "municipio": "Caparrapí"},
    {"departamento": "Cundinamarca", "municipio": "Cáqueza"},
    {"departamento": "Cundinamarca", "municipio": "Carmen de Carupa"},
    {"departamento": "Cundinamarca", "municipio": "Chaguaní"},
    {"departamento": "Cundinamarca", "municipio": "Chía"},
    {"departamento": "Cundinamarca", "municipio": "Chipaque"},
    {"departamento": "Cundinamarca", "municipio": "Choachí"},
    {"departamento": "Cundinamarca", "municipio": "Chocontá"},
    {"departamento": "Cundinamarca", "municipio": "Cogua"},
    {"departamento": "Cundinamarca", "municipio": "Cota"},
    {"departamento": "Cundinamarca", "municipio": "Cucunubá"},
    {"departamento": "Cundinamarca", "municipio": "El Colegio"},
    {"departamento": "Cundinamarca", "municipio": "El Peñón"},
    {"departamento": "Cundinamarca", "municipio": "El Rosal"},
    {"departamento": "Cundinamarca", "municipio": "Facatativá"},
    {"departamento": "Cundinamarca", "municipio": "Fómeque"},
    {"departamento": "Cundinamarca", "municipio": "Fosca"},
    {"departamento": "Cundinamarca", "municipio": "Funza"},
    {"departamento": "Cundinamarca", "municipio": "Fúquene"},
    {"departamento": "Cundinamarca", "municipio": "Fusagasugá"},
    {"departamento": "Cundinamarca", "municipio": "Gachalá"},
    {"departamento": "Cundinamarca", "municipio": "Gachancipá"},
    {"departamento": "Cundinamarca", "municipio": "Gachetá"},
    {"departamento": "Cundinamarca", "municipio": "Gama"},
    {"departamento": "Cundinamarca", "municipio": "Girardot"},
    {"departamento": "Cundinamarca", "municipio": "Granada"},
    {"departamento": "Cundinamarca", "municipio": "Guachetá"},
    {"departamento": "Cundinamarca", "municipio": "Guaduas"},
    {"departamento": "Cundinamarca", "municipio": "Guasca"},
    {"departamento": "Cundinamarca", "municipio": "Guataquí"},
    {"departamento": "Cundinamarca", "municipio": "Guatavita"},
    {"departamento": "Cundinamarca", "municipio": "Guayabal de Síquima"},
    {"departamento": "Cundinamarca", "municipio": "Guayabetal"},
    {"departamento": "Cundinamarca", "municipio": "Gutiérrez"},
    {"departamento": "Cundinamarca", "municipio": "Jerusalén"},
    {"departamento": "Cundinamarca", "municipio": "Junín"},
    {"departamento": "Cundinamarca", "municipio": "La Calera"},
    {"departamento": "Cundinamarca", "municipio": "La Mesa"},
    {"departamento": "Cundinamarca", "municipio": "La Palma"},
    {"departamento": "Cundinamarca", "municipio": "La Peña"},
    {"departamento": "Cundinamarca", "municipio": "La Vega"},
    {"departamento": "Cundinamarca", "municipio": "Lenguazaque"},
    {"departamento": "Cundinamarca", "municipio": "Machetá"},
    {"departamento": "Cundinamarca", "municipio": "Madrid"},
    {"departamento": "Cundinamarca", "municipio": "Manta"},
    {"departamento": "Cundinamarca", "municipio": "Medina"},
    {"departamento": "Cundinamarca", "municipio": "Mosquera"},
    {"departamento": "Cundinamarca", "municipio": "Nariño"},
    {"departamento": "Cundinamarca", "municipio": "Nemocón"},
    {"departamento": "Cundinamarca", "municipio": "Nilo"},
    {"departamento": "Cundinamarca", "municipio": "Nimaima"},
    {"departamento": "Cundinamarca", "municipio": "Nocaima"},
    {"departamento": "Cundinamarca", "municipio": "Pacho"},
    {"departamento": "Cundinamarca", "municipio": "Paime"},
    {"departamento": "Cundinamarca", "municipio": "Pandi"},
    {"departamento": "Cundinamarca", "municipio": "Paratebueno"},
    {"departamento": "Cundinamarca", "municipio": "Pasca"},
    {"departamento": "Cundinamarca", "municipio": "Puerto Salgar"},
    {"departamento": "Cundinamarca", "municipio": "Pulí"},
    {"departamento": "Cundinamarca", "municipio": "Quebradanegra"},
    {"departamento": "Cundinamarca", "municipio": "Quetame"},
    {"departamento": "Cundinamarca", "municipio": "Quipile"},
    {"departamento": "Cundinamarca", "municipio": "Rafael Reyes"},
    {"departamento": "Cundinamarca", "municipio": "Ricaurte"},
    {"departamento": "Cundinamarca", "municipio": "San Antonio del Tequendama"},
    {"departamento": "Cundinamarca", "municipio": "San Bernardo"},
    {"departamento": "Cundinamarca", "municipio": "San Cayetano"},
    {"departamento": "Cundinamarca", "municipio": "San Francisco"},
    {"departamento": "Cundinamarca", "municipio": "San Juan de Rioseco"},
    {"departamento": "Cundinamarca", "municipio": "Sasaima"},
    {"departamento": "Cundinamarca", "municipio": "Sesquilé"},
    {"departamento": "Cundinamarca", "municipio": "Sibaté"},
    {"departamento": "Cundinamarca", "municipio": "Silvania"},
    {"departamento": "Cundinamarca", "municipio": "Simijaca"},
    {"departamento": "Cundinamarca", "municipio": "Soacha"},
    {"departamento": "Cundinamarca", "municipio": "Sopó"},
    {"departamento": "Cundinamarca", "municipio": "Subachoque"},
    {"departamento": "Cundinamarca", "municipio": "Suesca"},
    {"departamento": "Cundinamarca", "municipio": "Supatá"},
    {"departamento": "Cundinamarca", "municipio": "Susa"},
    {"departamento": "Cundinamarca", "municipio": "Sutatausa"},
    {"departamento": "Cundinamarca", "municipio": "Tabio"},
    {"departamento": "Cundinamarca", "municipio": "Tausa"},
    {"departamento": "Cundinamarca", "municipio": "Tena"},
    {"departamento": "Cundinamarca", "municipio": "Tenjo"},
    {"departamento": "Cundinamarca", "municipio": "Tibacuy"},
    {"departamento": "Cundinamarca", "municipio": "Tibirita"},
    {"departamento": "Cundinamarca", "municipio": "Tocaima"},
    {"departamento": "Cundinamarca", "municipio": "Tocancipá"},
    {"departamento": "Cundinamarca", "municipio": "Topaipí"},
    {"departamento": "Cundinamarca", "municipio": "Ubalá"},
    {"departamento": "Cundinamarca", "municipio": "Ubaque"},
    {"departamento": "Cundinamarca", "municipio": "Ubaté"},
    {"departamento": "Cundinamarca", "municipio": "Une"},
    {"departamento": "Cundinamarca", "municipio": "Útica"},
    {"departamento": "Cundinamarca", "municipio": "Venecia"},
    {"departamento": "Cundinamarca", "municipio": "Vergara"},
    {"departamento": "Cundinamarca", "municipio": "Vianí"},
    {"departamento": "Cundinamarca", "municipio": "Villa de San Diego de Ubaté"},
    {"departamento": "Cundinamarca", "municipio": "Villagómez"},
    {"departamento": "Cundinamarca", "municipio": "Villapinzón"},
    {"departamento": "Cundinamarca", "municipio": "Villeta"},
    {"departamento": "Cundinamarca", "municipio": "Viotá"},
    {"departamento": "Cundinamarca", "municipio": "Yacopí"},
    {"departamento": "Cundinamarca", "municipio": "Zipacón"},
    {"departamento": "Cundinamarca", "municipio": "Zipaquirá"},
    # GUAINÍA
    {"departamento": "Guainía", "municipio": "Inírida"},
    # GUAVIARE
    {"departamento": "Guaviare", "municipio": "San José del Guaviare"},
    {"departamento": "Guaviare", "municipio": "Calamar"},
    {"departamento": "Guaviare", "municipio": "El Retorno"},
    {"departamento": "Guaviare", "municipio": "Miraflores"},
    # HUILA
    {"departamento": "Huila", "municipio": "Neiva"},
    {"departamento": "Huila", "municipio": "Acevedo"},
    {"departamento": "Huila", "municipio": "Agrado"},
    {"departamento": "Huila", "municipio": "Aipe"},
    {"departamento": "Huila", "municipio": "Algeciras"},
    {"departamento": "Huila", "municipio": "Altamira"},
    {"departamento": "Huila", "municipio": "Baraya"},
    {"departamento": "Huila", "municipio": "Campoalegre"},
    {"departamento": "Huila", "municipio": "Colombia"},
    {"departamento": "Huila", "municipio": "Elías"},
    {"departamento": "Huila", "municipio": "Garzón"},
    {"departamento": "Huila", "municipio": "Gigante"},
    {"departamento": "Huila", "municipio": "Guadalupe"},
    {"departamento": "Huila", "municipio": "Hobo"},
    {"departamento": "Huila", "municipio": "Iquira"},
    {"departamento": "Huila", "municipio": "Isnos"},
    {"departamento": "Huila", "municipio": "La Argentina"},
    {"departamento": "Huila", "municipio": "La Plata"},
    {"departamento": "Huila", "municipio": "Nataga"},
    {"departamento": "Huila", "municipio": "Oporapa"},
    {"departamento": "Huila", "municipio": "Paicol"},
    {"departamento": "Huila", "municipio": "Palermo"},
    {"departamento": "Huila", "municipio": "Palestina"},
    {"departamento": "Huila", "municipio": "Pital"},
    {"departamento": "Huila", "municipio": "Pitalito"},
    {"departamento": "Huila", "municipio": "Rivera"},
    {"departamento": "Huila", "municipio": "Saladoblanco"},
    {"departamento": "Huila", "municipio": "San Agustín"},
    {"departamento": "Huila", "municipio": "Santa María"},
    {"departamento": "Huila", "municipio": "Suaza"},
    {"departamento": "Huila", "municipio": "Tarqui"},
    {"departamento": "Huila", "municipio": "Tesalia"},
    {"departamento": "Huila", "municipio": "Tello"},
    {"departamento": "Huila", "municipio": "Teruel"},
    {"departamento": "Huila", "municipio": "Timaná"},
    {"departamento": "Huila", "municipio": "Villavieja"},
    {"departamento": "Huila", "municipio": "Yaguará"},
    # LA GUAJIRA
    {"departamento": "La Guajira", "municipio": "Riohacha"},
    {"departamento": "La Guajira", "municipio": "Albania"},
    {"departamento": "La Guajira", "municipio": "Barrancas"},
    {"departamento": "La Guajira", "municipio": "Dibulla"},
    {"departamento": "La Guajira", "municipio": "Distracción"},
    {"departamento": "La Guajira", "municipio": "El Molino"},
    {"departamento": "La Guajira", "municipio": "Fonseca"},
    {"departamento": "La Guajira", "municipio": "Hatonuevo"},
    {"departamento": "La Guajira", "municipio": "La Jagua del Pilar"},
    {"departamento": "La Guajira", "municipio": "Maicao"},
    {"departamento": "La Guajira", "municipio": "Manaure"},
    {"departamento": "La Guajira", "municipio": "San Juan del Cesar"},
    {"departamento": "La Guajira", "municipio": "Uribia"},
    {"departamento": "La Guajira", "municipio": "Urumita"},
    {"departamento": "La Guajira", "municipio": "Villanueva"},
    # MAGDALENA
    {"departamento": "Magdalena", "municipio": "Santa Marta"},
    {"departamento": "Magdalena", "municipio": "Algarrobo"},
    {"departamento": "Magdalena", "municipio": "Aracataca"},
    {"departamento": "Magdalena", "municipio": "Cerro de San Antonio"},
    {"departamento": "Magdalena", "municipio": "Ciénaga"},
    {"departamento": "Magdalena", "municipio": "El Banco"},
    {"departamento": "Magdalena", "municipio": "El Piñón"},
    {"departamento": "Magdalena", "municipio": "El Retén"},
    {"departamento": "Magdalena", "municipio": "Fundación"},
    {"departamento": "Magdalena", "municipio": "Guamal"},
    {"departamento": "Magdalena", "municipio": "Nueva Granada"},
    {"departamento": "Magdalena", "municipio": "Pedraza"},
    {"departamento": "Magdalena", "municipio": "Pivijay"},
    {"departamento": "Magdalena", "municipio": "Plato"},
    {"departamento": "Magdalena", "municipio": "Pueblo Viejo"},
    {"departamento": "Magdalena", "municipio": "Remolino"},
    {"departamento": "Magdalena", "municipio": "Sabanas de San Ángel"},
    {"departamento": "Magdalena", "municipio": "Salamina"},
    {"departamento": "Magdalena", "municipio": "San Sebastián de Buenavista"},
    {"departamento": "Magdalena", "municipio": "San Zenón"},
    {"departamento": "Magdalena", "municipio": "Santa Ana"},
    {"departamento": "Magdalena", "municipio": "Santa Bárbara de Pinto"},
    {"departamento": "Magdalena", "municipio": "Sitionuevo"},
    {"departamento": "Magdalena", "municipio": "Tenerife"},
    {"departamento": "Magdalena", "municipio": "Zapayán"},
    {"departamento": "Magdalena", "municipio": "Zona Bananera"},
    # META
    {"departamento": "Meta", "municipio": "Villavicencio"},
    {"departamento": "Meta", "municipio": "Acacías"},
    {"departamento": "Meta", "municipio": "Barranca de Upía"},
    {"departamento": "Meta", "municipio": "Castilla la Nueva"},
    {"departamento": "Meta", "municipio": "El Calvario"},
    {"departamento": "Meta", "municipio": "El Castillo"},
    {"departamento": "Meta", "municipio": "El Dorado"},
    {"departamento": "Meta", "municipio": "Fuente de Oro"},
    {"departamento": "Meta", "municipio": "Granada"},
    {"departamento": "Meta", "municipio": "Guamal"},
    {"departamento": "Meta", "municipio": "La Macarena"},
    {"departamento": "Meta", "municipio": "La Uribe"},
    {"departamento": "Meta", "municipio": "Lejanías"},
    {"departamento": "Meta", "municipio": "Mapiripán"},
    {"departamento": "Meta", "municipio": "Mesetas"},
    {"departamento": "Meta", "municipio": "Puerto Concordia"},
    {"departamento": "Meta", "municipio": "Puerto Gaitán"},
    {"departamento": "Meta", "municipio": "Puerto Lleras"},
    {"departamento": "Meta", "municipio": "Puerto López"},
    {"departamento": "Meta", "municipio": "Puerto Rico"},
    {"departamento": "Meta", "municipio": "Restrepo"},
    {"departamento": "Meta", "municipio": "San Carlos de Guaroa"},
    {"departamento": "Meta", "municipio": "San Juan de Arama"},
    {"departamento": "Meta", "municipio": "San Juanito"},
    {"departamento": "Meta", "municipio": "San Martín"},
    {"departamento": "Meta", "municipio": "Vistahermosa"},
    # NARIÑO
    {"departamento": "Nariño", "municipio": "Pasto"},
    {"departamento": "Nariño", "municipio": "Ipiales"},
    {"departamento": "Nariño", "municipio": "Tumaco"},
    {"departamento": "Nariño", "municipio": "Túquerres"},
    {"departamento": "Nariño", "municipio": "La Unión"},
    {"departamento": "Nariño", "municipio": "Samaniego"},
    {"departamento": "Nariño", "municipio": "Barbacoas"},
    {"departamento": "Nariño", "municipio": "Cumbal"},
    {"departamento": "Nariño", "municipio": "El Charco"},
    {"departamento": "Nariño", "municipio": "La Cruz"},
    {"departamento": "Nariño", "municipio": "Ricaurte"},
    {"departamento": "Nariño", "municipio": "San Andrés de Tumaco"},
    {"departamento": "Nariño", "municipio": "Sandoná"},
    # NORTE DE SANTANDER
    {"departamento": "Norte de Santander", "municipio": "Cúcuta"},
    {"departamento": "Norte de Santander", "municipio": "Ocaña"},
    {"departamento": "Norte de Santander", "municipio": "Pamplona"},
    {"departamento": "Norte de Santander", "municipio": "Tibú"},
    {"departamento": "Norte de Santander", "municipio": "Cáchira"},
    {"departamento": "Norte de Santander", "municipio": "Chinácota"},
    {"departamento": "Norte de Santander", "municipio": "El Zulia"},
    {"departamento": "Norte de Santander", "municipio": "Los Patios"},
    {"departamento": "Norte de Santander", "municipio": "Salazar"},
    {"departamento": "Norte de Santander", "municipio": "Villa del Rosario"},
    # PUTUMAYO
    {"departamento": "Putumayo", "municipio": "Mocoa"},
    {"departamento": "Putumayo", "municipio": "Colón"},
    {"departamento": "Putumayo", "municipio": "Orito"},
    {"departamento": "Putumayo", "municipio": "Puerto Asís"},
    {"departamento": "Putumayo", "municipio": "Puerto Caicedo"},
    {"departamento": "Putumayo", "municipio": "Puerto Guzmán"},
    {"departamento": "Putumayo", "municipio": "Puerto Leguízamo"},
    {"departamento": "Putumayo", "municipio": "San Francisco"},
    {"departamento": "Putumayo", "municipio": "San Miguel"},
    {"departamento": "Putumayo", "municipio": "Santiago"},
    {"departamento": "Putumayo", "municipio": "Sibundoy"},
    {"departamento": "Putumayo", "municipio": "Valle del Guamuez"},
    {"departamento": "Putumayo", "municipio": "Villagarzón"},
    # QUINDÍO
    {"departamento": "Quindío", "municipio": "Armenia"},
    {"departamento": "Quindío", "municipio": "Buenavista"},
    {"departamento": "Quindío", "municipio": "Calarcá"},
    {"departamento": "Quindío", "municipio": "Circasia"},
    {"departamento": "Quindío", "municipio": "Córdoba"},
    {"departamento": "Quindío", "municipio": "Filandia"},
    {"departamento": "Quindío", "municipio": "Génova"},
    {"departamento": "Quindío", "municipio": "La Tebaida"},
    {"departamento": "Quindío", "municipio": "Montenegro"},
    {"departamento": "Quindío", "municipio": "Pijao"},
    {"departamento": "Quindío", "municipio": "Quimbaya"},
    {"departamento": "Quindío", "municipio": "Salento"},
    # RISARALDA
    {"departamento": "Risaralda", "municipio": "Pereira"},
    {"departamento": "Risaralda", "municipio": "Apía"},
    {"departamento": "Risaralda", "municipio": "Balboa"},
    {"departamento": "Risaralda", "municipio": "Belén de Umbría"},
    {"departamento": "Risaralda", "municipio": "Dosquebradas"},
    {"departamento": "Risaralda", "municipio": "Guática"},
    {"departamento": "Risaralda", "municipio": "La Celia"},
    {"departamento": "Risaralda", "municipio": "La Virginia"},
    {"departamento": "Risaralda", "municipio": "Marsella"},
    {"departamento": "Risaralda", "municipio": "Mistrató"},
    {"departamento": "Risaralda", "municipio": "Pueblo Rico"},
    {"departamento": "Risaralda", "municipio": "Quinchía"},
    {"departamento": "Risaralda", "municipio": "Santa Rosa de Cabal"},
    {"departamento": "Risaralda", "municipio": "Santuario"},
    # SAN ANDRÉS Y PROVIDENCIA
    {"departamento": "San Andrés y Providencia", "municipio": "San Andrés"},
    {"departamento": "San Andrés y Providencia", "municipio": "Providencia"},
    # SANTANDER
    {"departamento": "Santander", "municipio": "Bucaramanga"},
    {"departamento": "Santander", "municipio": "Barrancabermeja"},
    {"departamento": "Santander", "municipio": "Floridablanca"},
    {"departamento": "Santander", "municipio": "Girón"},
    {"departamento": "Santander", "municipio": "Piedecuesta"},
    {"departamento": "Santander", "municipio": "San Gil"},
    {"departamento": "Santander", "municipio": "Socorro"},
    {"departamento": "Santander", "municipio": "Vélez"},
    {"departamento": "Santander", "municipio": "Barbosa"},
    {"departamento": "Santander", "municipio": "Betulia"},
    {"departamento": "Santander", "municipio": "Charalá"},
    {"departamento": "Santander", "municipio": "Cimitarra"},
    {"departamento": "Santander", "municipio": "Lebrija"},
    {"departamento": "Santander", "municipio": "Málaga"},
    {"departamento": "Santander", "municipio": "Mogotes"},
    {"departamento": "Santander", "municipio": "Páez"},
    {"departamento": "Santander", "municipio": "Puerto Wilches"},
    {"departamento": "Santander", "municipio": "Sabana de Torres"},
    {"departamento": "Santander", "municipio": "San Andrés"},
    {"departamento": "Santander", "municipio": "Zapatoca"},
    # SUCRE
    {"departamento": "Sucre", "municipio": "Sincelejo"},
    {"departamento": "Sucre", "municipio": "Corozal"},
    {"departamento": "Sucre", "municipio": "Sampués"},
    {"departamento": "Sucre", "municipio": "San Marcos"},
    {"departamento": "Sucre", "municipio": "Tolú"},
    {"departamento": "Sucre", "municipio": "Buenavista"},
    {"departamento": "Sucre", "municipio": "Caimito"},
    {"departamento": "Sucre", "municipio": "Chalán"},
    {"departamento": "Sucre", "municipio": "Coloso"},
    {"departamento": "Sucre", "municipio": "Coveñas"},
    {"departamento": "Sucre", "municipio": "El Roble"},
    {"departamento": "Sucre", "municipio": "Galeras"},
    {"departamento": "Sucre", "municipio": "Guaranda"},
    {"departamento": "Sucre", "municipio": "La Unión"},
    {"departamento": "Sucre", "municipio": "Los Palmitos"},
    {"departamento": "Sucre", "municipio": "Majagual"},
    {"departamento": "Sucre", "municipio": "Morroa"},
    {"departamento": "Sucre", "municipio": "Ovejas"},
    {"departamento": "Sucre", "municipio": "Palmito"},
    {"departamento": "Sucre", "municipio": "San Benito Abad"},
    {"departamento": "Sucre", "municipio": "San Juan de Betulia"},
    {"departamento": "Sucre", "municipio": "San Luis de Sincé"},
    {"departamento": "Sucre", "municipio": "San Onofre"},
    {"departamento": "Sucre", "municipio": "San Pedro"},
    {"departamento": "Sucre", "municipio": "Santiago de Tolú"},
    {"departamento": "Sucre", "municipio": "Sucre"},
    {"departamento": "Sucre", "municipio": "Tolú Viejo"},
    # TOLIMA
    {"departamento": "Tolima", "municipio": "Ibagué"},
    {"departamento": "Tolima", "municipio": "Espinal"},
    {"departamento": "Tolima", "municipio": "Melgar"},
    {"departamento": "Tolima", "municipio": "Honda"},
    {"departamento": "Tolima", "municipio": "Chaparral"},
    {"departamento": "Tolima", "municipio": "Fresno"},
    {"departamento": "Tolima", "municipio": "Líbano"},
    {"departamento": "Tolima", "municipio": "Mariquita"},
    {"departamento": "Tolima", "municipio": "Planadas"},
    {"departamento": "Tolima", "municipio": "Purificación"},
    {"departamento": "Tolima", "municipio": "Rovira"},
    # VALLE DEL CAUCA
    {"departamento": "Valle del Cauca", "municipio": "Cali"},
    {"departamento": "Valle del Cauca", "municipio": "Buenaventura"},
    {"departamento": "Valle del Cauca", "municipio": "Palmira"},
    {"departamento": "Valle del Cauca", "municipio": "Tuluá"},
    {"departamento": "Valle del Cauca", "municipio": "Cartago"},
    {"departamento": "Valle del Cauca", "municipio": "Buga"},
    {"departamento": "Valle del Cauca", "municipio": "Jamundí"},
    {"departamento": "Valle del Cauca", "municipio": "Yumbo"},
    {"departamento": "Valle del Cauca", "municipio": "Roldanillo"},
    {"departamento": "Valle del Cauca", "municipio": "Caicedonia"},
    {"departamento": "Valle del Cauca", "municipio": "Candelaria"},
    {"departamento": "Valle del Cauca", "municipio": "El Cerrito"},
    {"departamento": "Valle del Cauca", "municipio": "Florida"},
    {"departamento": "Valle del Cauca", "municipio": "Ginebra"},
    {"departamento": "Valle del Cauca", "municipio": "La Cumbre"},
    {"departamento": "Valle del Cauca", "municipio": "La Unión"},
    {"departamento": "Valle del Cauca", "municipio": "Pradera"},
    {"departamento": "Valle del Cauca", "municipio": "San Pedro"},
    {"departamento": "Valle del Cauca", "municipio": "Sevilla"},
    {"departamento": "Valle del Cauca", "municipio": "Zarzal"},
    # VAUPÉS
    {"departamento": "Vaupés", "municipio": "Mitú"},
    # VICHADA
    {"departamento": "Vichada", "municipio": "Puerto Carreño"},
    {"departamento": "Vichada", "municipio": "Cumaribo"},
    {"departamento": "Vichada", "municipio": "La Primavera"},
    {"departamento": "Vichada", "municipio": "Santa Rosalía"},
]


def get_municipios():
    """Retorna la lista completa de municipios filtrada de entradas placeholder."""
    return [m for m in MUNICIPIOS_COLOMBIA if "va el resto" not in m["municipio"]]


if __name__ == "__main__":
    municipios = get_municipios()
    print(f"Total municipios: {len(municipios)}")
    depts = set(m["departamento"] for m in municipios)
    print(f"Departamentos: {len(depts)}")
